name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  push-to-hf-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Hugging Face remote
        run: |
          git remote add hf https://dhruvkej9:${{ secrets.HUGGINGFACE_TOKEN }}@huggingface.co/spaces/dhruvkej9/my-gnn-backend

      - name: Push to Hugging Face Space
        run: |
          git push hf main --force
